/**
 * ASCII portrait, derived from the cut-out character render.
 *
 * Generated by downsampling the alpha-masked PNG and mapping luminance onto a
 * ramp. The ramp deliberately excludes < > & and quotes so these lines drop
 * straight into SVG text without escaping.
 *
 * 59 columns x 50 rows.
 */
export const ASCII_PORTRAIT = [
  '                             #h2h355',
  '                         MBM22i:i;;r;rs2',
  '                       2335:......::..,:;s',
  '                       @5.:,.  .,, .,  ...iA3',
  '                      S@;i,   .iXsi:: ,... :2',
  '                      G#: :;rXA533hGHs:,...,s2',
  '                       HShr:sH2, Ah5S93;:, .s',
  '                         @2sH@BS3SB@@B9srXr;2',
  '                         @@#G3M@@@@@@#S2MM9M',
  '                         @@SAA2hM@@#GH52S#S',
  '                          @95AhGHS#GM3XA52',
  '                          @@Bs3GGh5Ar;sH5',
  '                            9X,,...:iXH#H',
  '                            @@i;:,rMHG###',
  '                           BsrrsXAA3HHGHsr',
  '                         h#i;iirhSM33HM5; ;A',
  '                    @BM5X;.;i:   ;hGMGh3A. :;s',
  '               @9Gh32sii;i;::,..  .3##S9Ss:,.:XA2',
  '             @HAriiiirirrrriirrr;,,.:G@@H;:;;;;irsAhG',
  '            @G:;irrr;irrrrrrrrrrr;:iisB@s.:iirrriiiis2',
  '            H:;;;iiii:irrrrrrrrrrri:iiMG,irrrrrrii;;;iA',
  '           M;:;;:;i;;,:rirrrrrrrrrri;;irirrrrirrii;;;:r',
  '           2::;;,::,:,,;iirrrrrrrrrrii:;riiiiiiiii;:::i',
  '          2X:,:i:.,.. ,::;iirrrrrrriii:;iiiiii;;;i;.,:;r',
  '          Hr:,,;;,..  ..,,::;iiiriiii;:ii;;;;;;;;i, .,;i',
  '          3:;:.:::,,   ...,,:;;iiiiiii;irii;;;;;;:  ,::r',
  '         Mi;;;:::::,    ..,,,::;iiiii;;iii;;;;;;;. .::;is',
  '        9X;i;;;;:,,.    .,,,,,,:;rii;;:;;iii;;:::  .:;;;r',
  '        5;iii;;;:,.   ,,,,,,,,:::;rii;:;iiiii;;;:  ,:;;;i',
  '        r.:;,,,,:,,,  .,;i;;::::,:;iii;;i;;;i;;;,  .,::;X',
  '       h;,,:;::,. ss.   .,;iii;::,,:;i;:iii;;;;;,  ,:,..XM',
  '       s:;;::,,.. ss::.    .:irri;:::;i;iiiiii;;.  .,,,,,r',
  '       A..,,,. ..r52.,;:;;:,..:;irii;;;;;iiri:,::  ...,,,r',
  '      2;.,,:;;:, s5MMHh,,,,:;;;;;irrrii;,iii;::,:  .,;ii;:s',
  '       ;..,;iiii:;A55:    ..,::,...,:;;;.,;;;i;:: .,::;;;;;',
  '       ;,::;;;;ii,,X. .,:;:::::::::,..,:::::::;i:  :s53A:,:',
  '       i,.,,:r3##MiX2r,,,:;;;;;iiiiiii;:,,;:,,..,,s2H9BS3,:',
  '        ;,..s5M#@BG2i    .,;iii;;::,,,,,. ;;,,,,..i2M##Hh',
  '          . rA5hG99Gr .:;;;;;;;:::::;;;ii. ;ii;;;::sh##Gh',
  '              X23HS99A.,;;;;;;ii;iiiiiiii;. :iii;i;,X##H',
  '               A23MG9@M;::;;;iiii;i;;;iiiii, ,iiii:::AA35',
  '                XXhMGHXri;:;;;irriiiii;;;rir; ,;;;;;:iss2',
  '                 .;32;iirrrri;;;;iiiiiii;iiir: :;:;;iii:s',
  '                  .r:,;iirrrrrri::,,:;iii;;i;i:,:;iriii;',
  '                  2s.,:;;irrriiiii;:,,:;:;:;;;iiiiiii;i',
  '                  B2.,:::;;;ii;;:::::::,,,:;;;;;;;ii;:;',
  '                  3r,,:::;;;;;;;:::,,,,.,:,,,:;;iii;:;i',
  '                  s::,,:;;;;;;;;;::,..    .,:;;;;;;::;r',
  '                  5;::;;:;iiiiii;;:,.    ..,,::;;;::,;r',
  '                 G2::;;;,;;iii;::,..     .,::;;;::::..;i',
];

export const ASCII_COLS = Math.max(...ASCII_PORTRAIT.map((l) => l.length));
export const ASCII_ROWS = ASCII_PORTRAIT.length;
