/**
 * Unique-visitor counter for the public site. Admin-only — nothing is shown to
 * visitors.
 *
 * The unit is the *device*, not the network. Identity comes from an opaque
 * random id the browser generates once and keeps in localStorage, which is the
 * only approach that gets the two cases that matter right:
 *
 *   - the same person reloading, or coming back next week, counts once;
 *   - two people behind one office IP count as two.
 *
 * IP-based counting fails the second badly — a whole company collapses into a
 * single visitor — and fingerprinting fails it differently while being far more
 * invasive. A random id stored client-side is both more accurate here and the
 * least identifying option: it carries no personal data, is scoped to this site,
 * and cannot be correlated with anything else.
 *
 * Known limits, none of which are fixable without asking people to log in:
 * a second browser on the same machine reads as a second device, private
 * windows count each visit, and clearing site data resets the id.
 */

const TOTAL = 'visitors:unique';
const VISITS = 'visitors:visits';
const seenKey = (id) => `visitor:${id}`;
const dayKey = (d) => `visitors:day:${d}`;

// A device is remembered for a year; after that a returning visitor counts
// again, which is the same convention analytics tools use for a "unique".
const REMEMBER_SECONDS = 365 * 24 * 60 * 60;
const DAY_SECONDS = 60 * 60 * 24 * 90; // daily buckets kept for 90 days

/** Ids are generated by us; anything else is a client bug or someone poking. */
const VALID_ID = /^[0-9a-f-]{16,64}$/i;

/**
 * Crawlers mostly never run the script that calls this, so this is a backstop
 * for the ones that do rather than the primary defence.
 */
const BOT = /bot|crawl|spider|slurp|bing|baidu|yandex|duckduck|facebookexternalhit|headless|lighthouse|preview|monitor|curl|wget|python-requests/i;

const today = () => new Date().toISOString().slice(0, 10);

/**
 * KV has no atomic increment and is eventually consistent, so simultaneous
 * first-visits can read the same value and write the same result. At portfolio
 * traffic the drift is negligible, and the alternative — a Durable Object — is
 * a lot of machinery for a number only the owner ever sees.
 */
async function bump(env, key, ttl) {
  const next = Number((await env.CACHE.get(key)) || 0) + 1;
  await env.CACHE.put(key, String(next), ttl ? { expirationTtl: ttl } : undefined);
  return next;
}

/**
 * Records a page view. Returns what happened, so the caller can decide whether
 * to respond differently — currently it does not, and the endpoint stays silent
 * either way so the count is not scriptable from the outside.
 */
export async function recordVisit(env, { deviceId, userAgent = '' }) {
  if (!deviceId || !VALID_ID.test(deviceId)) return { counted: false, reason: 'bad-id' };
  if (BOT.test(userAgent)) return { counted: false, reason: 'bot' };

  // Every hit bumps the raw total; only the first from a device bumps uniques.
  await bump(env, VISITS);

  const seen = await env.CACHE.get(seenKey(deviceId));
  if (seen) return { counted: false, reason: 'returning' };

  await env.CACHE.put(seenKey(deviceId), '1', { expirationTtl: REMEMBER_SECONDS });
  await bump(env, TOTAL);
  await bump(env, dayKey(today()), DAY_SECONDS);

  return { counted: true };
}

/** Everything the admin dashboard needs, in one read. */
export async function visitorStats(env) {
  const days = [];
  for (let i = 0; i < 7; i += 1) {
    const d = new Date();
    d.setUTCDate(d.getUTCDate() - i);
    days.push(d.toISOString().slice(0, 10));
  }

  const [unique, visits, ...daily] = await Promise.all([
    env.CACHE.get(TOTAL),
    env.CACHE.get(VISITS),
    ...days.map((d) => env.CACHE.get(dayKey(d))),
  ]);

  const perDay = days.map((date, i) => ({ date, count: Number(daily[i] || 0) }));

  return {
    unique: Number(unique || 0),
    visits: Number(visits || 0),
    today: perDay[0].count,
    last7: perDay.reduce((sum, d) => sum + d.count, 0),
    // Oldest first reads more naturally in a chart.
    daily: perDay.slice().reverse(),
  };
}
